import type { ProfessionalContent } from "../types/professional";

export const professionalContent: ProfessionalContent = {
	identity: {
		name: "Davi Naizer",
		headline: "Senior Frontend & Product Engineer",
		location: "Hove, United Kingdom",
		profileLinks: [
			{
				label: "LinkedIn",
				url: "https://www.linkedin.com/in/davi-naizer",
			},
			{
				label: "GitHub",
				url: "https://github.com/davinaizer",
			},
		],
	},
	summary: {
		summary:
			"Senior frontend and product engineer with experience building product applications, internal tools and the delivery systems behind them. Most of my commercial experience has been with React, TypeScript and JavaScript, while more recently I've been building a native iOS application using Swift and SwiftUI. Throughout my career, I've worked across the product lifecycle, contributing to product development while improving the engineering systems that support software delivery. As I took on more responsibility, I found myself increasingly drawn to frontend architecture, developer tooling, workflow automation and broader product ownership, with a focus on reducing complexity and making software easier to build, maintain and evolve. I naturally gravitate towards recurring sources of friction. Whether that's delivering product features, improving engineering workflows or building internal tools, I enjoy understanding how people work and finding practical ways to make that work simpler.",
		homeExcerpt:
			"Hi, I’m Davi. I’m a frontend and product engineer who enjoys understanding how things work, fixing what gets in the way, and building software that is genuinely useful. Most of my commercial work has been with React, TypeScript and JavaScript, and more recently I’ve been building native iOS applications with SwiftUI.",
		personalNote:
			"Away from work, you’ll find me cooking, making espresso, or with my wife and daughter, ideally with good music on. The take-it-apart-and-see-how-it-works habit never left, so I keep a few independent experiments where I try ideas out for the fun of it.",
		focusAreas: [
			"Frontend architecture",
			"Product development",
			"Developer tooling",
			"Workflow automation",
			"Engineering practices",
		],
	},
	experience: [
		{
			slug: "independent-product-venture-product-engineer-co-creator-2025",
			company: "Independent Product Project",
			role: "Product Engineer & Co-creator",
			startDate: "01/2026",
			responsibilities: [
				"Building Alfred, an AI-powered activity recommendation and planning product with another engineer, spanning a C#/.NET backend, native iOS application and React/TypeScript web client and dashboard. I lead development of the iOS application while collaborating on architecture, testing, integration and shared product direction across the three systems. Parts of the web client were implemented with AI assistance and validated through testing and architectural review. The application is currently undergoing private TestFlight validation ahead of its first public release.",
			],
			contributions: [
				"Built the native iOS application, delivering the first end-to-end mobile experience across onboarding, authentication, recommendations and planning workflows.",
				"Collaborated on architecture, testing and cross-system integration across the C#/.NET backend, native iOS application and React/TypeScript web client.",
				"Developed reusable, accessible UI components with consistent theming and Dynamic Type support, making the interface easier to build, maintain and evolve.",
				"Designed the iOS application's layered architecture using MVVM-style presentation, repositories, use cases and dependency injection.",
				"Integrated backend services for authentication, real-time updates, deep linking and application state while maintaining clear boundaries between networking, domain logic and presentation.",
				"Added automated tests across the presentation, domain, data and infrastructure layers.",
			],
			technologies: [
				"Swift",
				"SwiftUI",
				"React",
				"TypeScript",
				"C#/.NET",
				"REST APIs",
				"Firebase",
				"XCTest",
				"XcodeGen",
				"GitHub",
				"GitLab",
			],
		},
		{
			slug: "self-employed-planned-career-break-2024-2025",
			company: "Self-employed",
			role: "Career Break",
			startDate: "11/2024",
			endDate: "12/2025",
			responsibilities: ["Took a career break after leaving The Signal Group."],
			contributions: [],
			technologies: [],
		},
		{
			slug: "signal-group-senior-frontend-software-engineer-2023-2024",
			company: "The Signal Group",
			role: "Senior Frontend Software Engineer",
			startDate: "12/2023",
			endDate: "10/2024",
			location: "London, UK",
			responsibilities: [
				"Worked on Signal Ocean, a maritime intelligence platform used by brokers, operators and analysts to monitor global shipping activity. As part of a cross-functional product team, I worked on the Vessel List area within a large fullstack monorepo. One recurring challenge was that creating reusable Vessel List templates required support requests and manual engineering work. We redesigned that workflow into a self-service experience that allowed company administrators to create and manage templates directly.",
			],
			contributions: [
				"Developed the frontend implementation of the Template Admin experience, taking the feature through implementation, testing, fixes and production release, including permission-aware creation, editing, validation and deletion flows integrated with frontend state and metadata-driven APIs.",
				"Built data-intensive Vessels List configuration workflows using AG Grid, including role-based editing, validation, read-only and deletion states, and reusable editing behaviours.",
				"Maintained shared UI components across dashboards, forms and administration surfaces, including migrations away from deprecated components.",
				"Maintained focused tests and snapshots and addressed type, lint, SonarLint and refactoring issues during frontend feature development.",
				"Onboarded a frontend engineer to the monorepo, Vessel List architecture and Azure-based development environment.",
			],
			technologies: [
				"React",
				"TypeScript",
				"MobX",
				"OpenLayers",
				"AG Grid",
				"C#",
				".NET",
				"Azure DevOps",
				"REST APIs",
			],
		},
		{
			slug: "ballys-interactive-frontend-tech-lead-2022-2023",
			company: "Bally's Interactive",
			role: "Frontend Tech Lead",
			startDate: "11/2022",
			endDate: "11/2023",
			location: "London, UK",
			responsibilities: [
				"Provided technical direction across frontend initiatives focused on code quality, developer experience, onboarding and platform modernisation. Worked with Product, Technical Architects and engineering teams to improve frontend architecture, engineering standards and delivery practices across multiple products.",
			],
			contributions: [
				"Mapped dependencies and technical debt across the BMC reward-component architecture, identifying duplicated logic, legacy constraints and reusable abstractions to guide modernisation.",
				"Defined a frontend code-quality standardisation programme covering 13 frameworks, tools and shared libraries, introducing consistent linting, formatting, commit validation, Pull Request automation and static analysis.",
				"Integrated SonarQube with GitHub Actions and Pull Request decoration, investigating monorepo test-reporting issues affecting quality-gate adoption.",
				"Created a structured onboarding programme covering repositories, architecture, production workflows and developer setup, including automated repository discovery through Confluence.",
				"Owned the Scrum backlog and roadmap, providing technical direction during planning, refinement and delivery while defining technical stories to prioritise platform improvements alongside product work.",
			],
			technologies: [
				"React",
				"TypeScript",
				"Redux Toolkit",
				"Nx",
				"GitHub Actions",
				"SonarQube",
				"Jenkins",
				"Storybook",
				"Node.js",
				"GitHub Enterprise REST APIs",
			],
		},
		{
			slug: "gamesys-ballys-senior-frontend-engineer-2020-2022",
			company: "Gamesys / Bally's Interactive",
			role: "Senior Frontend Engineer",
			startDate: "10/2020",
			endDate: "11/2022",
			location: "London, UK",
			responsibilities: [
				"Worked across customer-facing products and internal engineering tooling, increasingly focusing on developer experience, workflow automation and frontend platform improvements.",
			],
			contributions: [
				"Built a React preview application for validating generated promotional UI against real configuration before release, and maintained shared configuration infrastructure used by multiple delivery tools.",
				"Built a Node.js tool around the Jira REST API that reduced a promotional content workflow from days to minutes.",
				"Created a Node.js CLI that generated version-pinned promotional UI from templates and automated pull-request-based delivery; migrated it to TypeScript and introduced supporting CI and release practices.",
				"Created onboarding guides, architecture documentation and dependency maps that helped engineers understand large projects more quickly.",
				"Supported the team through mentoring, code reviews and production troubleshooting.",
			],
			technologies: [
				"React",
				"JavaScript",
				"Styled-components",
				"Node.js",
				"Redux",
				"GitHub REST API",
				"Jenkins",
				"Jira REST API",
			],
		},
		{
			slug: "gamesys-frontend-developer-2019-2020",
			company: "Gamesys",
			role: "Frontend Developer",
			startDate: "03/2019",
			endDate: "09/2020",
			location: "London, UK",
			responsibilities: [
				"Joined the Promotions team building customer-facing promotional experiences before expanding into frontend architecture, developer tooling and cross-team enablement.",
			],
			contributions: [
				"Led the technical improvement initiative for Landing Pages, defining the proposed frontend architecture, documenting the roadmap and presenting the approach to engineering, QA, design and business stakeholders.",
				"Contributed to a configuration-driven promotional UI framework and reusable components used across multiple consumer brands, helping non-engineers compose and deliver promotional experiences without changing application code.",
				"Built reusable frontend components and styling foundations to improve consistency across promotional interfaces.",
				"Contributed to customer-facing React applications while helping improve internal engineering tooling and workflows.",
				"Mentored developers, designers and stakeholders through code reviews, frontend debugging, Git support and technical documentation.",
			],
			technologies: [
				"React",
				"JavaScript",
				"Redux",
				"Webpack",
				"Sass",
				"Node.js",
			],
		},
		{
			slug: "self-employed-frontend-developer-2017-2019",
			company: "Self-employed",
			role: "Freelance Frontend Developer",
			startDate: "07/2017",
			endDate: "02/2019",
			location: "Brazil",
			responsibilities: [
				"I worked as a freelancer on frontend and online learning projects.",
			],
			contributions: [],
			technologies: [],
		},
		{
			slug: "unbox-design-studio-co-founder-technical-lead-2009-2017",
			company: "UNBOX Design Studio",
			role: "Co-founder & Frontend Developer",
			startDate: "10/2009",
			endDate: "03/2017",
			location: "Brazil",
			responsibilities: [
				"Co-founded a technology and design studio delivering digital learning platforms, Learning Management Systems (LMS), and interactive educational products for Fortune 500 and global enterprise clients, including Volvo Brasil, Grupo Boticário, MetLife, HSBC, and Electrolux. Worked across product discovery, solution design, technical leadership, frontend development, and client delivery as part of a founding team comprising a computer engineer, a UX designer, and a graphic designer.",
			],
			contributions: [
				"Worked directly with clients, designers and instructional specialists to translate business and learning requirements into practical software solutions.",
				"Led technical delivery of client projects, coordinating a team of up to five developers while remaining hands-on with architecture, frontend development and implementation.",
				"Reduced e-learning delivery time from around three months to about four weeks by building a JSFL script that extracted copy, content and images directly from the Flash design source files into dynamic, XML-driven content, replacing what had been a manual conversion step.",
				"Built browser-based learning platforms, interactive educational products and custom Learning Management System (LMS) functionality for enterprise projects.",
			],
			technologies: ["JavaScript", "HTML", "CSS", "ActionScript", "Moodle"],
		},
	],
	earlierCareer: [
		{
			slug: "gpac-lead-web-developer-2007-2009",
			company: "Grupo GPAC Comunicação Integrada",
			role: "Lead Web Developer",
			startDate: "07/2007",
			endDate: "07/2009",
			location: "Brazil",
			responsibilities: [
				"I worked on web and digital learning projects and took on team lead responsibilities.",
			],
			contributions: [],
			technologies: [],
		},
		{
			slug: "hsbc-training-development-analyst-2005-2007",
			company: "HSBC Bank Brasil",
			role: "Training & Development Analyst",
			startDate: "07/2005",
			endDate: "07/2007",
			location: "Brazil",
			responsibilities: [
				"I built tools for learning content and supported the Learning Management System (LMS).",
			],
			contributions: [],
			technologies: [],
		},
		{
			slug: "gpac-web-developer-2001-2005",
			company: "Grupo GPAC Comunicação Integrada",
			role: "Web Developer",
			startDate: "09/2001",
			endDate: "07/2005",
			location: "Brazil",
			responsibilities: [
				"I developed web applications and digital learning content.",
			],
			contributions: [],
			technologies: [],
		},
		{
			slug: "omni-technical-support-2000-2001",
			company: "Omni Informática Ltda.",
			role: "Technical Support",
			startDate: "01/2000",
			endDate: "08/2001",
			location: "Brazil",
			responsibilities: [
				"I handled computer, network, video-editing, and Apple desktop support.",
			],
			contributions: [],
			technologies: [],
		},
		{
			slug: "sy-megasoft-computer-support-1998-1999",
			company: "SY-MEGASOFT",
			role: "Computer Support",
			startDate: "04/1998",
			endDate: "04/1999",
			location: "Brazil",
			responsibilities: ["I worked in computer support."],
			contributions: [],
			technologies: [],
		},
	],
	claims: [],
	resume: {
		label: "Download Resume",
		url: "/davi-naizer-resume.pdf",
		updatedAt: "2026-09-29",
	},
	contact: [
		{
			label: "Email",
			url: "mailto:davi.naizer@gmail.com",
			category: "Direct",
			actionLabel: "Send an email",
			description: "The best way to reach me directly.",
		},
		{
			label: "LinkedIn",
			url: "https://www.linkedin.com/in/davi-naizer",
			category: "Professional profile",
			actionLabel: "View LinkedIn profile",
			description: "More about my work and professional experience.",
		},
	],
};
